GET http://localhost:5050/users

###

POST http://localhost:5050/users
Content-Type: application/json

{
    "username": "new_user",
    "email": "new_user@example.com"
}

### 

# Obtener todos los productos
GET http://localhost:5050/products

###

# Obtener productos con precio menor a 50
GET http://localhost:5050/products/price/50

###

# Obtener solo username y email de todos los usuarios
GET http://localhost:5050/users/fields

###

# Obtener órdenes ordenadas por fecha descendente
GET http://localhost:5050/orders/by-date

###

# Enviar evento para cambiar pantalla
POST http://localhost:5050/change-screen
Content-Type: application/json

{}